### ISSUE TITLE
Add tags in selection for different modes

### ISSUE THREAD

**Issue by KappaDistributive** [KappaDistributive/gotypist#34]
In the selection view, add tags to communicate to the user which mode that particular lesson uses. Right now, there are two options:

- `Prose` and
- `Dash`.

Refer to the README for their definition.

**Comment by nandhithakamal** [comment]
From what I understand, if the user chooses Top 300 words (or any file from Bag of Words directory), that would be the `Dash` mode.
Any file from the Lessons directory would be the `Prose` mode. 
Please let me know if my understanding of the modes is correct.

**Comment by KappaDistributive** [comment]
@nandhithakamal Sorry for the slow reply. You're spot on :-)

Not sure how to best visualize this, though. If you have an idea, please feel free to create a PR and we'll take it from there.

**Comment by nandhithakamal** [comment]
@KappaDistributive I have indeed added a PR. It's very basic though. Do take a look at it. https://github.com/KappaDistributive/gotypist/pull/38

**Comment by KappaDistributive** [comment]
Closed by #38
